### ISSUE TITLE
Possible install script bug

### ISSUE THREAD

**Issue by JoshuaBThompson** [DyCI/dyci-main#100]
Mac OS X El Capitan:
When running the install.sh script in the Install directory, the cp commands without sudo in front (cp clang-real, clang-real++ and clang.backup) failed due to lack of permissions.
The script then continue to replace the clang in my /Applications/Xcode.app/..../usr/bin/clang with the dyci-clang.py which looks for clang-real, clang.backup...etc but does not find it since the cp commands did not execute. 

Using the /user/bin/clang in root did not work as a python exception occurred during runtime.
The only that solution that worked for me:
1. had to reinstall Xcode to get the original clang back
2. added sudo to the cp commands for clang-real, clang.back and clang-real++

**Comment by PaulTaykalo** [comment]
@JoshuaBThompson Thanks for the input.
Consider using `./install.sh -s` if you're using Xcode only
https://github.com/DyCI/dyci-main/wiki/Installation#xcode-only-

**Comment by PaulTaykalo** [comment]
@JoshuaBThompson 
Fixed in https://github.com/DyCI/dyci-main/commit/db2b9df366adcc4a6c5e23c6803b3cbc85a2df9b
Thanks.
