### ISSUE TITLE
Xcode 8 support ?

### ISSUE THREAD

**Issue by kaustubh-kabra** [DyCI/dyci-main#111]
I ran a sample project from unsigned Xcode 8 installed with DyCI plugin. After injecting source, the console mentions injection is successful but I do not see any change on simulator. The operation done was simply changing background color of a Single Page app.
Please let know if I am missing anything.

**Comment by lysongzi** [comment]
i have meet this question too. 
and i get some log like
 "Couldn't load file Error : dlopen(/Users/bingolin/.dyci/dyci5411718.dylib, 10): no suitable image found.  Did find: /Users/bingolin/.dyci/dyci5411718.dylib: required code signature missing for '/Users/bingolin/.dyci/dyci5411718.dylib'"

env: iOS Simulator OSX 10.12.3 xcode8.2.1 

= =.so i also want to ask xcode 8 support ????

**Comment by PaulTaykalo** [comment]
@lysongzi please update the latest to xcode plugin and say if it works for you.
https://github.com/DyCI/dyci-xcode-plugin/commit/094dd0373eea824b0754df781a27b69f2bbba11a

**Comment by PaulTaykalo** [comment]
@kaustubh-kabra updated please take a look

**Comment by lysongzi** [comment]
cooool! it works on demo project
but in my project , i get this log:
Couldn't load file Error : dlopen(/Users/bingolin/.dyci/dyci1809190.dylib, 10): Symbol not found: _OBJC_CLASS_$_XXXXXXX Referenced from: /Users/bingolin/.dyci/dyci1809190.dylib Expected in: flat namespace in /Users/xxxxxx/.dyci/dyci1809190.dylib

**Comment by aspcartman** [comment]
Not working for me

**Comment by aspcartman** [comment]
Fixed by explicitly signing in dyci-recompile.py:222

```python
+ [DYCI_ROOT_DIR + "/tmp/" + libraryName]\
+ ['-v']


# print "Linker args \n%s" % ' '.join(linkArgs)
runAndFailOnError(linkArgs)
print "Linked\n"

#sign
signArgs = ["/usr/bin/codesign"] + ["-s"] + ["-"] + ["-vvvv"] + ["-f"] + [DYCI_ROOT_DIR + "/tmp/" + libraryName]
runAndFailOnError(signArgs)
print "Signed " + libraryName + "\n"

runAndFailOnError(["mv", DYCI_ROOT_DIR + "/tmp/" + libraryName, DYCI_ROOT_DIR + "/" + libraryName])
```

File watcher needs to be modified. It looks for file creation events (?) and signing the file inplace (without tmp directory) results in a .cstmp file creation, which yields a file watcher event, who in the result tries to inject a not yet signed binary. Used this hack instead.

**Comment by PaulTaykalo** [comment]
@aspcartman could you make a PR with a fix?

**Comment by aspcartman** [comment]
Yes I may. Question is, how could this possibly work before? iOS does not allow dlopen() of unsigned binaries after iOS8.x. Is your iPhone jailbroken?

Reopen this issue please

**Comment by PaulTaykalo** [comment]
Well, It was never designed to be working on device, to prevent occasional submissions with dyci enabled.

**Comment by aspcartman** [comment]
I am talking about the simulator - it is applied to it too. I was not trying to run this on the actual device. You haven't ever had a problem with signing?

**Comment by PaulTaykalo** [comment]
@aspcartman the latest plugin for xcode contains signing phase. Are you using the last one?

**Comment by aspcartman** [comment]
I certainly have the latest one, yes (verified with the latest commit), but I'm injecting through AppCode and have no xcode launched. I was searching for a problem there at first, but found `dyci-recompile.py` and continued with it.

**Comment by PaulTaykalo** [comment]
Oh.. I got it.. you're signin it in the script, instead of in Xcode.
well.. if that works for the AppCode I believe it's fine to move it in the script instead.

**Comment by aspcartman** [comment]
Awesome. I will make a pr soon, need to fix the file watcher first.

**Comment by aspcartman** [comment]
Didn't find a correct way of fixing of the FileWatcher.

**Comment by RomanTruba** [comment]
I still can't make it work in Xcode 8. ^X doesn't work
