### ISSUE TITLE
how to use dyci in XCode 8.2.1

### ISSUE THREAD

**Issue by saeid-rez** [DyCI/dyci-main#113]
hi
the hot key ^x not work and in Product menu i cant find dyci menu!
i use installation guide to install dyci and add pod to project successfully.
what is the problem?

**Comment by saeid-rez** [comment]
![screen shot 2017-05-17 at 12 59 11 pm](https://cloud.githubusercontent.com/assets/5124098/26145207/d5ea6d30-3b00-11e7-92e2-538729f89bc1.png)

here is result of install.sh command

**Comment by PaulTaykalo** [comment]
Unfortunately, Xcode8+ doesn't support custom plugins. You either need to use unsigned version of Xcode or try another tool :)
