### ISSUE TITLE
Autosave on CTRL + X ?

### ISSUE THREAD

**Issue by skrew** [DyCI/dyci-main#49]
Hi, fantastic job, really !

It's there a way to auto save when pressing CTRL + X ? It's not easy to CMD+S and CTRL +X each time, or i have a problem with my installation ?

Thanks

**Comment by PaulTaykalo** [comment]
Merged In in https://github.com/DyCI/dyci-main/commit/710b3b9c5cc93e00114a8231565f333cd0212896
