### ISSUE TITLE
Crash while injecting storyboard

### ISSUE THREAD

**Issue by onivem** [DyCI/dyci-main#70]
After I'm saving a storyboard and trying to inject it, application is crashing with the following error: Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UIProxyObject 0x7bff9e90> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key collectionView.'
Does DYCI supports storyboards?

**Comment by PaulTaykalo** [comment]
Only some simple injections.  
If the question is "Does DYCI track any possible stroyboard changes" - The answer is NO.

**Comment by frowing** [comment]
@onivem I'm getting the same error. I'm curious to know if you found the issue causing the crash.

**Comment by frowing** [comment]
@PaulTaykalo I'm getting this error every time I try to inject the storyboard. I've examined and all the outlets are properly set. Any more ideas what could be causing this? 

Except for this issue, I'm really, really, really, REALLY loving dyic-main. Thank you!

**Comment by PaulTaykalo** [comment]
There's no work in progress for allowing storyboard injection.
They have kind'a complex structure and it's hard to track changes were made

**Comment by frowing** [comment]
@PaulTaykalo is it much harder than xibs? Xibs do work, right?

**Comment by PaulTaykalo** [comment]
Depending on your definition of done :)
I would rather say that xibs do work sometimes. Still, there are tons of possible cases when they won't work.
