### ISSUE TITLE
Tag the current version of DyCI

### ISSUE THREAD

**Issue by PBruce** [DyCI/dyci-main#71]
We're using the `master` version of DyCI. It would be great if you could tag it with a version number so we can depend on the specific version instead of having to use `master`.

Thanks for a great library!

**Comment by petergp** [comment]
+1

**Comment by PaulTaykalo** [comment]
Well, this one is easy :)  
https://github.com/DyCI/dyci-main/releases/tag/v0.1.5.7

**Comment by PBruce** [comment]
Thanks :)
