### ISSUE TITLE
Inject *.json files in bundle

### ISSUE THREAD

**Issue by hfossli** [DyCI/dyci-main#73]
What is needed in order to be able inject json files in to bundle?

**Comment by hfossli** [comment]
Is this line all it takes?
https://github.com/DyCI/dyci-main/blob/b994c1b69d604aac6a8b6a5e5c3b58ae52d30629/Scripts/dyci-recompile.py#L117

**Comment by PaulTaykalo** [comment]
Fixed here https://github.com/DyCI/dyci-main/pull/74 I suppose
