### ISSUE TITLE
Support for Xcode 6.2

### ISSUE THREAD

**Issue by PBruce** [DyCI/dyci-main#75]
Xcode 6.2 seems to have a UUID that you haven't added yet, as per your explanation here:

https://github.com/DyCI/dyci-main/wiki/Troubleshooting

I added this manually to the `Info.plist` and it seems to work great:

```
<string>A16FF353-8441-459E-A50C-B071F53F51B7</string>
```

**Comment by PaulTaykalo** [comment]
Fixed in 03eceeca296dbdce2cae62a32f8384096b31ecff

**Comment by PBruce** [comment]
Thanks!
