### ISSUE TITLE
Does not install on Xcode 6.3

### ISSUE THREAD

**Issue by nickbit** [DyCI/dyci-main#78]
After doing a clean install of Xcode 6.3 and installing DyCI (DYCI was successfully installed!) the Inject menu item does not appear. Any thoughts?

**Comment by PaulTaykalo** [comment]
Fixed in https://github.com/DyCI/dyci-main/commit/0f03a803bbad5b90d15022b52609aa68b8262ab6
Each new version of Xcode requires to update plugins Info.plist. You can do it manually by adding required string to Info.plist, or redownload and install dyci
