### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by ssuchanowski** [DyCI/dyci-main#80]
File /Users/sebos/Workspace/Spray/ios/Files/Spray/Classes/InboxCell.m was not injected successfully Traceback (most recent call last): File "/Users/sebos/.dyci/scripts/dyci-recompile.py", line 177, in   runAndFailOnError(compileString) File "/Users/sebos/.dyci/scripts/dyci-recompile.py", line 19, in runAndFailOnError stderr=subprocess.PIPE) File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 709, in __init__ errread, errwrite) File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1326, in _execute_child raise child_exceptionOSError: [Errno 2] No such file or directory

**Comment by PaulTaykalo** [comment]
@ssuchanowski reinstall dyci. It seems that you don't have it correctly installed.  
Also make sure, that `xcode-select` is pointing on the correct Xcode version

**Comment by ssuchanowski** [comment]
worked ;)
thanks!
