### ISSUE TITLE
CocoaPods: Unable to find a specification for `DyCI`

### ISSUE THREAD

**Issue by nickbit** [DyCI/dyci-main#82]
Tried to update the installation with `pod update` and the message
```Unable to find a specification for 'DyCI'``` appears
Same happens for `pod install`

**Comment by PaulTaykalo** [comment]
@nickbit What string do you have in `Podfile`?

**Comment by nickbit** [comment]
pod 'DyCI'

**Comment by PaulTaykalo** [comment]
Where did you get this line from?

**Comment by PaulTaykalo** [comment]
`pod 'dyci', :git => 'https://github.com/DyCI/dyci-main.git'`
OR
`pod 'dyci'`
These will work

**Comment by nickbit** [comment]
Great, thank you.
I think I got this from the documentation. Can you check and correct if appropriate?

**Comment by PaulTaykalo** [comment]
If you can me give a link where did you found this one, I will
