### ISSUE TITLE
Getting failed to inject code issue

### ISSUE THREAD

**Issue by paritsohraval100** [DyCI/dyci-main#85]
Getting Red dote with

Couldn't load index file '/Users/paritoshraval/.dyci/index/e6130ba5ea97b4e47a5751c29c67eaaa' (/Users/paritoshraval/Desktop/Old Desktop/Old Code/Codes1/MyTest123/MyTest123/ViewController.m). Use default compilation instead

I am using subproject and clean , successfully compile it. but even getting issue.I am using xcode 6.3

Please help.

**Comment by PaulTaykalo** [comment]
Have you tried this? https://github.com/DyCI/dyci-main/wiki/Troubleshooting  
Have you ran installer `install.sh` ?

**Comment by paritsohraval100** [comment]
Hey,

Thanks for your reply.
Yes i have tried both. If i am not wrong i ran installer install.sh by

git clone https://github.com/DyCI/dyci-main.git
cd dyci-main/Install/
./install.sh

Thanks again,
Paritosh

On Tue, May 26, 2015 at 11:54 PM, Paul Taykalo <notifications@github.com>
wrote:

> Have you tried this?
> https://github.com/DyCI/dyci-main/wiki/Troubleshooting
>
> Have you ran installer install.sh ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DyCI/dyci-main/issues/85#issuecomment-105624777>.
>



-- 
Thanks & Regards,
Paritosh Raval

**Comment by paritsohraval100** [comment]
Event i am getting error with your example

Ld
/Users/paritoshraval/Library/Developer/Xcode/DerivedData/dyci-example-cxquexzdxtimuvgqrlvbxmjkzwcl/Build/Products/Debug-iphonesimulator/dyci-example.app/dyci-example
normal x86_64

    cd "/Users/paritoshraval/Desktop/Dyci/dyci-main-master/Dynamic Code
Injection/dyci-example"

    export IPHONEOS_DEPLOYMENT_TARGET=6.0

    export
PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"


/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-arch x86_64 -isysroot
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk
-L/Users/paritoshraval/Library/Developer/Xcode/DerivedData/dyci-example-cxquexzdxtimuvgqrlvbxmjkzwcl/Build/Products/Debug-iphonesimulator
-F/Users/paritoshraval/Library/Developer/Xcode/DerivedData/dyci-example-cxquexzdxtimuvgqrlvbxmjkzwcl/Build/Products/Debug-iphonesimulator
-filelist
/Users/paritoshraval/Library/Developer/Xcode/DerivedData/dyci-example-cxquexzdxtimuvgqrlvbxmjkzwcl/Build/Intermediates/dyci-example.build/Debug-iphonesimulator/dyci-example.build/Objects-normal/x86_64/dyci-example.LinkFileList
-Xlinker -objc_abi_version -Xlinker 2 -ldyci -ObjC -fobjc-arc
-fobjc-link-runtime -Xlinker -no_implicit_dylibs
-mios-simulator-version-min=6.0 -ldyci -framework UIKit -framework
Foundation -framework CoreGraphics -framework QuartzCore -Xlinker
-dependency_info -Xlinker
/Users/paritoshraval/Library/Developer/Xcode/DerivedData/dyci-example-cxquexzdxtimuvgqrlvbxmjkzwcl/Build/Intermediates/dyci-example.build/Debug-iphonesimulator/dyci-example.build/Objects-normal/x86_64/dyci-example_dependency_info.dat
-o
/Users/paritoshraval/Library/Developer/Xcode/DerivedData/dyci-example-cxquexzdxtimuvgqrlvbxmjkzwcl/Build/Products/Debug-iphonesimulator/dyci-example.app/dyci-example


ld: library not found for -ldyci

clang: error: linker command failed with exit code 1 (use -v to see
invocation)

On Wed, May 27, 2015 at 10:00 AM, Paritosh Raval <paritoshraval100@gmail.com
> wrote:

>
>
> Hey,
>
> Thanks for your reply.
> Yes i have tried both. If i am not wrong i ran installer install.sh by
>
> git clone https://github.com/DyCI/dyci-main.git
> cd dyci-main/Install/
> ./install.sh
>
> Thanks again,
> Paritosh
>
> On Tue, May 26, 2015 at 11:54 PM, Paul Taykalo <notifications@github.com>
> wrote:
>
>> Have you tried this?
>> https://github.com/DyCI/dyci-main/wiki/Troubleshooting
>>
>> Have you ran installer install.sh ?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/DyCI/dyci-main/issues/85#issuecomment-105624777>.
>>
>
>
>
> --
> Thanks & Regards,
> Paritosh Raval
>
>


-- 
Thanks & Regards,
Paritosh Raval

**Comment by paritsohraval100** [comment]
Hey Paul,

Sorry if i am disturbing you but i am really excited about this great
tutorial.
Why i am sending a mail again , I did same thing with Xcode 6.2 and
everything is working.

I am getting above issues with only Xcode 6.3.So What i need to do to fix
this in Xcode 6.3 ?

Thanks
Paritosh



On Wed, May 27, 2015 at 10:18 AM, Paritosh Raval <paritoshraval100@gmail.com
> wrote:

> Event i am getting error with your example
>
> Ld
> /Users/paritoshraval/Library/Developer/Xcode/DerivedData/dyci-example-cxquexzdxtimuvgqrlvbxmjkzwcl/Build/Products/Debug-iphonesimulator/dyci-example.app/dyci-example
> normal x86_64
>
>     cd "/Users/paritoshraval/Desktop/Dyci/dyci-main-master/Dynamic Code
> Injection/dyci-example"
>
>     export IPHONEOS_DEPLOYMENT_TARGET=6.0
>
>     export
> PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
>
>
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
> -arch x86_64 -isysroot
> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk
> -L/Users/paritoshraval/Library/Developer/Xcode/DerivedData/dyci-example-cxquexzdxtimuvgqrlvbxmjkzwcl/Build/Products/Debug-iphonesimulator
> -F/Users/paritoshraval/Library/Developer/Xcode/DerivedData/dyci-example-cxquexzdxtimuvgqrlvbxmjkzwcl/Build/Products/Debug-iphonesimulator
> -filelist
> /Users/paritoshraval/Library/Developer/Xcode/DerivedData/dyci-example-cxquexzdxtimuvgqrlvbxmjkzwcl/Build/Intermediates/dyci-example.build/Debug-iphonesimulator/dyci-example.build/Objects-normal/x86_64/dyci-example.LinkFileList
> -Xlinker -objc_abi_version -Xlinker 2 -ldyci -ObjC -fobjc-arc
> -fobjc-link-runtime -Xlinker -no_implicit_dylibs
> -mios-simulator-version-min=6.0 -ldyci -framework UIKit -framework
> Foundation -framework CoreGraphics -framework QuartzCore -Xlinker
> -dependency_info -Xlinker
> /Users/paritoshraval/Library/Developer/Xcode/DerivedData/dyci-example-cxquexzdxtimuvgqrlvbxmjkzwcl/Build/Intermediates/dyci-example.build/Debug-iphonesimulator/dyci-example.build/Objects-normal/x86_64/dyci-example_dependency_info.dat
> -o
> /Users/paritoshraval/Library/Developer/Xcode/DerivedData/dyci-example-cxquexzdxtimuvgqrlvbxmjkzwcl/Build/Products/Debug-iphonesimulator/dyci-example.app/dyci-example
>
>
> ld: library not found for -ldyci
>
> clang: error: linker command failed with exit code 1 (use -v to see
> invocation)
>
> On Wed, May 27, 2015 at 10:00 AM, Paritosh Raval <
> paritoshraval100@gmail.com> wrote:
>
>>
>>
>> Hey,
>>
>> Thanks for your reply.
>> Yes i have tried both. If i am not wrong i ran installer install.sh by
>>
>> git clone https://github.com/DyCI/dyci-main.git
>> cd dyci-main/Install/
>> ./install.sh
>>
>> Thanks again,
>> Paritosh
>>
>> On Tue, May 26, 2015 at 11:54 PM, Paul Taykalo <notifications@github.com>
>> wrote:
>>
>>> Have you tried this?
>>> https://github.com/DyCI/dyci-main/wiki/Troubleshooting
>>>
>>> Have you ran installer install.sh ?
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/DyCI/dyci-main/issues/85#issuecomment-105624777>.
>>>
>>
>>
>>
>> --
>> Thanks & Regards,
>> Paritosh Raval
>>
>>
>
>
> --
> Thanks & Regards,
> Paritosh Raval
>
>


-- 
Thanks & Regards,
Paritosh Raval

**Comment by PaulTaykalo** [comment]
Hm. so you have two xcodes?

**Comment by PaulTaykalo** [comment]
The thing is that when you're running `./install.sh` it's updates `clang` in your Xcode folder.   
Xcode folder is searched by `xcode-select` command-line tool. So in order to make this work correctly for both, you need to run `xcode-select -s <PATH_TO_XCODE>` before installation.

**Comment by paritsohraval100** [comment]
Yes, I have two xcodes.

On Wed, May 27, 2015 at 12:38 PM, Paul Taykalo <notifications@github.com>
wrote:

> Hm. so you have two xcodes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DyCI/dyci-main/issues/85#issuecomment-105788291>.
>



-- 
Thanks & Regards,
Paritosh Raval

**Comment by PaulTaykalo** [comment]
Feel free to reopen issue if the thing with `xcode-select` won't work  for you

**Comment by paritsohraval100** [comment]
I am not getting where i have to do this thing ? xcode-select -s
<PATH_TO_XCODE>

In my terminal?

If i do it in terminal it is showing errors.



On Wed, May 27, 2015 at 12:41 PM, Paul Taykalo <notifications@github.com>
wrote:

> The thing is that when you're running ./install.sh it's updates clang in
> your Xcode folder.
>
> Xcode folder is searched by xcode-select command-line tool. So in order
> to make this work correctly for both, you need to run xcode-select -s
> <PATH_TO_XCODE> before installation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DyCI/dyci-main/issues/85#issuecomment-105788756>.
>



-- 
Thanks & Regards,
Paritosh Raval

**Comment by PaulTaykalo** [comment]
You should put correct path there it should be something like  
`xcode-select -s /Applications/Xcode.app/Contents/Developer`

But it depends on where is your Xcode6.3 installed  

So the think is that "clang" got updated in Xcode 6.2 and it wasn't updated in Xcode 6.3 becuase dyci installator relies on `xcode-select`  

As an _another_ option you can try to checkout the latest experimental build `https://github.com/DyCI/dyci-main/tree/feature/xcode-plugin-compilation-flags` from here. run `./install.sh` and check again

**Comment by paritsohraval100** [comment]
I did xcode-select -s /Applications/Xcode.app/Contents/Developer

but it is showing error in terminal

xcode-select: error: --switch must be run as root (e.g. sudo xcode-select
--switch <xcode_folder_path>).

On Wed, May 27, 2015 at 10:32 PM, Paul Taykalo <notifications@github.com>
wrote:

> You should put correct path there it should be something like
>
> xcode-select -s /Applications/Xcode.app/Contents/Developer
>
> But it depends on where is your Xcode6.3 installed
>
> So the think is that "clang" got updated in Xcode 6.2 and it wasn't
> updated in Xcode 6.3 becuase dyci installator relies on xcode-select
>
> As an *another* option you can try to checkout the latest experimental
> build
> https://github.com/DyCI/dyci-main/tree/feature/xcode-plugin-compilation-flags
> from here. run ./install.sh and check again
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DyCI/dyci-main/issues/85#issuecomment-105995890>.
>



-- 
Thanks & Regards,
Paritosh Raval
