### ISSUE TITLE
DyCI problems with Xcode 6.3.2

### ISSUE THREAD

**Issue by nickbit** [DyCI/dyci-main#94]
After installing DyCI and opening Xcode 6.3.2 I got a warning if I surely want to enable DyCI plugin. After answering YES, and trying to compile the code, I got some clang errors (cannot recall what exactly now, need to reinstall DyCI again in order to get that info to you).
I tried to uninstall and the problems persisted.
Had to delete Xcode and reinstall it again.

Any other having these problems?
Is there any workaround?

**Comment by PaulTaykalo** [comment]
Are you referencing to this "issue" ? https://github.com/DyCI/dyci-main/issues/8    
https://github.com/DyCI/dyci-main#warning  

If it's your problem, then, as a "workaround" you can use  this   
https://github.com/DyCI/dyci-main/releases/tag/1.6

(TL;DR:)  Smply use `./install.sh -s` when installing dyci

**Comment by nickbit** [comment]
Yes that's the problem.
Thank you!

**Comment by PaulTaykalo** [comment]
Duplicated #8

**Comment by nickbit** [comment]
I downloaded the file and installed. Here is the log: 
```
== Backing up clang : grep -Fq == CLANG_PROXY == /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
cp: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang.backup: Permission denied
Done.
== Faking up clang : cp: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang.backup: No such file or directory
cp: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang.backup: No such file or directory
Password:
Done.
== Preparing dyci-recompile directories: Skipped. (Already prepared).
== Copying scripts : Done.
== AppCode 3.1 found. Installing DYCI as AppCode plugin : Done.
   Restart Appcode. Plugin should be loaded automaticaly. If not, you may need to install it manually
== Installing Xcode DYCI plugin : Done.
  Now you can use DYCI from the Xcode :P

DYCI was successfully installed!
Use (^X) hot key in your IDE to perform code injections. Have fun.
```
So there are permission denied errors.

I opened Xcode, the alert shows, I say YES, compile the code and the linker gives this error:
```
Cannot locate original clang and it's backup.
This can be because of Xcode update without dyci uninstallation.
In case, if you see this, clang is little broken now, and you need to update it manually
By running next command in your terminal : 
echo "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang-real" "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang.backup" | xargs -n 1 sudo cp /usr/bin/clang
```
Now I have to install Xcode from scratch again.
