### ISSUE TITLE
Issue with dyci installation on appcode

### ISSUE THREAD

**Issue by bolismauro** [DyCI/dyci-main#98]
Hello everyone.
So far I've used Xcode to develop my project and dyci worked fine (I've used the xcode only plugin).

In the last week I decided to switch to app code and therefore I removed the xcode only installtion of dyci and installed the one that works for both appcode and xcode (the one that replace clang I guess).

Once I did it I started receiving weird errors (both on appcode and xcode):
```
echo "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang-real" "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang.backup" | xargs -n 1 sudo cp /usr/bin/clang
```

I did it and from that moment both xcode and appcode stopped working (I press run, nothing happens and eventually xcode stop to respond).

I've removed dyci and reinstalling xcode right now.
I would like to use dyci on app chode though, is there any change to have a working installation?

Thanks!

**Comment by PaulTaykalo** [comment]
Hi there. It seems, well, I'm pretty sure that you've experienced [this issue](https://github.com/DyCI/dyci-main/issues/8)
This happen from time to time, and the only way for now - is to reinstall Xcode.
Somehow clang backing up twice, and then no real-clang left.
After clean Xcode Install 
`./install.sh` should work correctly for you.
make backup of clang somewhere in another directory for now.
I'll try to check what' going on there
