### ISSUE TITLE
Installation / uninstallation completely screws up clang

### ISSUE THREAD

**Issue by fatuhoku** [DyCI/dyci-main#99]
Using Xcode 6.4. I'm now left with a rather inconvenient task of figuring out what the hell dyci has done with clang, and how to make my toolchain work again :(

**Comment by fatuhoku** [comment]
```
xcrun -find clang                                                                  [2.1.5]
xcrun: error: unable to find utility "clang", not a developer tool or in PATH
```

**Comment by PaulTaykalo** [comment]
What have you done before this happened?  
What files do you have here?   
`xcode-select -print-path`/Toolchains/XcodeDefault.xctoolchain/usr/bin/

**Comment by fatuhoku** [comment]
Sorry, I wanted to get up and running ASAP and didn't take time to investigate. I've just reinstalled Xcode 6.4 to solve my issue.

**Comment by PaulTaykalo** [comment]
@fatuhoku Sorry to hear that.
Will recheck intallation/deinstallation process.
if you're using Xcode only, then, better install with `-s` flag, like described here  
https://github.com/DyCI/dyci-main/releases/tag/1.6
